import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import ThreeScene from '@/app/Pages/AnimatePg'
import TestAnimate from '@/app/Pages/AnimateTest'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TestAnimate />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
